# Generated by Django 3.0.3 on 2020-04-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucursal', models.CharField(max_length=5)),
                ('cartera', models.CharField(max_length=6)),
                ('clientes', models.CharField(max_length=150)),
                ('fecha_alta', models.CharField(default='', max_length=10)),
                ('saldo', models.FloatField()),
            ],
        ),
    ]
